print("-----Basic form-----")
username = input("Enter your name: ")
print("Hello, ",username)
useremail = input("Enter your email: ")
print("Email: ",useremail)
mobile = int(input("Enter your Mobile: "))
print("Keep giving the information :) ")
address = input("Enter your address: ")
print("on the way :)", end="\n\n\n\n")

print("\n\n\t\t\t**********Your Details**********")
print("\t\t\t---------------------------------")
print("\t\t\tName :", username)
print("\t\t\tEmail :", useremail)
print("\t\t\tMobile :", mobile)
print("\t\t\tAddress :", address)
print("\t\t\tThanks for providing details :)", end="\n\n\n\n")